title: Rodolfo Luis Tonoli
author:
  name: Rodolfo Luis Tonoli
  email: rltonoli@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
#I am a PhD candidate at UNICAMP and part of the Artificial Intelligence Lab, Recod.ai. My research interests include speech-driven animation, behavioral AI and machine learning. 

# Build settings

theme: minima

plugins:
#  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
 social_links:
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  - { platform: github,         user_url: "https://github.com/rltonoli" }
  - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=CR6MfGYAAAAJ&hl=en&oi=ao" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  - { platform: linkedin,       user_url: "https://www.linkedin.com/in/rodolfo-luis-tonoli-30a904a1/" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: x,              user_url: "https://x.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
 - _pages/about.md
 - _pages/phd.md
 - _pages/msc.md
 - _pages/other.md

markdown: kramdown

include: ['_pages', '_figs']
exclude: [vendor]

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
